ChatBotWithSignalR/Areas/Admin/Controllers/RoleController.cs
using ChatBotWithSignalR.Areas.Admin.Models;
using ChatBotWithSignalR.Constant;
using ChatBotWithSignalR.Helper;
using ChatBotWithSignalR.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChatBotWithSignalR.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IToastNotification _toast;

        public RoleController(RoleManager<IdentityRole> roleManager, IToastNotification toast)
        {
            _roleManager = roleManager;
            _toast = toast;
        }

        [Authorize(Permissions.IdentityRoles.View)]
        public async Task<IActionResult> Index() => View(await _roleManager.Roles.ToListAsync());

        [HttpPost]
        [Authorize(Permissions.IdentityRoles.Create)]
        public async Task<IActionResult> CreateOrEdit(string roleId, string roleName)
        {
            try
            {
                if (string.IsNullOrEmpty(roleId))
                {
                    var role = new IdentityRole(roleName);
                    await _roleManager.CreateAsync(role);
                    await _toast.Success("Role Created Successfully");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    var role = await _roleManager.FindByIdAsync(roleId);
                    if (role == null)
                    {
                        await _toast.Error("Role Not Found");
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        role.Name = roleName;
                        await _roleManager.UpdateAsync(role);
                        await _toast.Success($"Role Update Successfully");
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        [HttpPost]
        [Authorize(Permissions.IdentityRoles.Delete)]

        public async Task<IActionResult> Delete(string roleId)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(roleId);
                if (role == null)
                {
                    await _toast.Error("Role Not Found");
                    return RedirectToAction(nameof(Index));
                }
                await _roleManager.DeleteAsync(role);
                await _toast.Success($"Role ({role.Name}) Delete Successfully");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


        #region Manage Role Permissions/Claims

        [HttpGet]
        [Authorize(Permissions.ManageRoleClaims.View)]
        public async Task<IActionResult> OnGetRoleClaims(string roleId)
        {
            try
            {
                PermissionViewModel model = new PermissionViewModel { RoleId = roleId };

                //Get All Nested Module/Class Type
                var moduleTypeList = Permissions.GetAllNestedModuleType();

                // Get All Permission belongs to a nested module/class
                foreach (var module in moduleTypeList)
                {
                    model.RoleClaims.GetPermissions(module, roleId);
                }

                // Get the role by roleId
                var role = await _roleManager.FindByIdAsync(roleId);

                // Get All Claims/Permission of a particular role
                var roleClaims = await _roleManager.GetClaimsAsync(role);

                // Selected all the permission that are already assign in this role.
                foreach (var claim in roleClaims)
                {
                    var viewResult = model.RoleClaims.Where(x => x.ViewValue == claim.Value).FirstOrDefault();
                    if (viewResult is not null)
                    {
                        viewResult.IsViewSelected = true;
                    }

                    var createResult = model.RoleClaims.Where(x => x.CreateValue == claim.Value).FirstOrDefault();
                    if (createResult is not null)
                    {
                        createResult.IsCreateSelected = true;
                    }

                    var editResult = model.RoleClaims.Where(x => x.EditValue == claim.Value).FirstOrDefault();
                    if (editResult is not null)
                    {
                        editResult.IsEditSelected = true;
                    }

                    var deleteResult = model.RoleClaims.Where(x => x.DeleteValue == claim.Value).FirstOrDefault();
                    if (deleteResult is not null)
                    {
                        deleteResult.IsDeleteSelected = true;
                    }
                }
                return View("RoleClaims", model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        [Authorize(Permissions.ManageRoleClaims.Create)]
        public async Task<IActionResult> OnPostRoleClaims(PermissionViewModel model)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(model.RoleId);
                if (role == null)
                {
                    await _toast.Error("Role Not Found");
                    return RedirectToAction(nameof(Index));
                }

                // Remove all claim of this role
                var roleClaims = await _roleManager.GetClaimsAsync(role);
                foreach (var claim in roleClaims)
                {
                    await _roleManager.RemoveClaimAsync(role, claim);
                }

                // Get all selected permission
                var selectedClaims = model.RoleClaims.Where(c => c.IsViewSelected || c.IsCreateSelected || c.IsEditSelected || c.IsDeleteSelected).ToList();
                IdentityResult result = new();
                foreach (var claim in selectedClaims)
                {
                    if (claim.IsViewSelected)
                    {
                        result = await _roleManager.AddPermissionClaim(role, claim.ViewValue);
                    }

                    if (claim.IsCreateSelected)
                    {
                        result = await _roleManager.AddPermissionClaim(role, claim.CreateValue);
                    }

                    if (claim.IsEditSelected)
                    {
                        await _roleManager.AddPermissionClaim(role, claim.EditValue);
                    }

                    if (claim.IsDeleteSelected)
                    {
                        await _roleManager.AddPermissionClaim(role, claim.DeleteValue);
                    }
                }
                if (result.Succeeded)
                {
                    await _toast.Success($"Permissions Updated Successfully");
                    return View("RoleClaims", model);
                }
                await _toast.Error("Role Not Found");
                return View("RoleClaims", model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        #endregion
    }
}

ChatBotWithSignalR/Areas/Admin/Controllers/UserController.cs
using ChatBotWithSignalR.Areas.Admin.Models;
using ChatBotWithSignalR.Extensions;
using ChatBotWithSignalR.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using System.Text.Encodings.Web;
using System.Text;
using ChatBotWithSignalR.DTOs;
using ChatBotWithSignalR.Constant;

namespace ChatBotWithSignalR.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IToastNotification _toast;
        private readonly IWebHostEnvironment _webHost;
        private readonly IMailService _mailService;
        private readonly ILogger<UserController> _logger;

        public UserController(UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
            SignInManager<ApplicationUser> signInManager,
            IToastNotification toast,
            IWebHostEnvironment webHost,
            IMailService mailService,
            ILogger<UserController> logger)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _toast = toast;
            _webHost = webHost;
            _mailService = mailService;
            _logger = logger;
        }

        [HttpGet]
        [Authorize(Permissions.ApplicationUsers.View)]
        public IActionResult Index() => View();

        [HttpGet]
        public async Task<IActionResult> LoadUser(string roleId = "")
        {
            try
            {
                IList<ApplicationUser> users = new List<ApplicationUser>();
                List<ApplicationUserViewModel> userList = new();
                if (string.IsNullOrEmpty(roleId))
                    users = await _userManager.Users.ToListAsync();
                else
                {
                    var role = await _roleManager.FindByIdAsync(roleId);
                    users = await _userManager.GetUsersInRoleAsync(role?.Name ?? "");
                }
                foreach (var user in users)
                {
                    userList.Add(new ApplicationUserViewModel
                    {
                        Id = user.Id,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        UserName = user.UserName,
                        Email = user.Email,
                        PhoneNumber = user.PhoneNumber,
                        ProfilePhotoUrl = user.ProfilePhotoUrl,
                        Roles = string.Join(", ", await _userManager.GetRolesAsync(user))
                    });
                }
                return PartialView("_ViewAll", userList);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


        [HttpGet]
        [Authorize(Permissions.ApplicationUsers.Create)]
        [Authorize(Permissions.ApplicationUsers.Edit)]
        public async Task<IActionResult> OnCreateOrEdit(string userId = "")
        {
            try
            {
                if (string.IsNullOrEmpty(userId))
                {
                    return View("CreateOrEdit", new ApplicationUserViewModel());
                }
                else
                {
                    var user = await _userManager.FindByIdAsync(userId);
                    if (user == null)
                    {
                        await _toast.Error("User Not Found");
                        return RedirectToAction(nameof(Index));
                    }
                    ApplicationUserViewModel userViewModel = new ApplicationUserViewModel
                    {
                        Id = user.Id,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        UserName = user.UserName,
                        Email = user.Email,
                        PhoneNumber = user.PhoneNumber,
                        ProfilePhotoUrl = user.ProfilePhotoUrl,
                        Password = user.PasswordHash,
                    };
                    return View("CreateOrEdit", userViewModel);
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        [Authorize(Permissions.ApplicationUsers.Create)]
        public async Task<IActionResult> OnPostCreateOrEdit(ApplicationUserViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(model.Id))
                    {
                        ApplicationUser user = new();
                        user.FirstName = model.FirstName.Trim();
                        user.LastName = model.LastName.Trim();
                        user.UserName = model.UserName.Trim();
                        user.Email = model.Email.Trim();
                        user.PhoneNumber = model.PhoneNumber.Trim();
                        user.ProfilePhotoUrl = await SaveImageAsync(model.ProfilePhoto, user.UserName, 200, 200);
                        await _userManager.AddPasswordAsync(user, model.Password);
                        var result = await _userManager.CreateAsync(user, model.Password);
                        if (result.Succeeded)
                        {
                            await _toast.Success("User Create Successfully");
                            return RedirectToAction(nameof(Index));
                        }
                        await _toast.Error($"{result.Errors}");
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        var user = await _userManager.FindByIdAsync(model.Id);
                        if (user == null)
                        {
                            await _toast.Error("User Not Found");
                            return RedirectToAction(nameof(Index));
                        }
                        user.FirstName = model.FirstName.Trim();
                        user.LastName = model.LastName.Trim();
                        user.Email = model?.Email.Trim();
                        user.PhoneNumber = model?.PhoneNumber.Trim();
                        user.ProfilePhotoUrl = await SaveImageAsync(model.ProfilePhoto, model.UserName, 200, 200, model.ProfilePhotoUrl);
                        var result = await _userManager.UpdateAsync(user);
                        if (result.Succeeded)
                        {
                            await _toast.Success($"{user.UserName} Update Successfully");
                            return RedirectToAction(nameof(Index));
                        }
                        await _toast.Error($"{result.Errors}");
                        return RedirectToAction(nameof(Index));
                    }

                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }



        [HttpPost]
        [Authorize(Permissions.ApplicationUsers.Delete)]
        public async Task<IActionResult> OnPostUserDelete(string userId)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user == null)
                {
                    await _toast.Error("User Not Found");
                    return RedirectToAction(nameof(Index));
                }
                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    await _toast.Success($"{user.UserName} Deleted Successfully");
                    return RedirectToAction(nameof(Index));
                }
                await _toast.Error($"{result.Errors}");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        #region User Role Manage

        [HttpGet]
        [Authorize(Permissions.ManageUserRoles.View)]
        public async Task<IActionResult> OnGetUserRoles(string userId)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user == null)
                {
                    await _toast.Error("User Not Found");
                    return RedirectToAction(nameof(Index));
                }
                ApplicationUserViewModel userModel = new()
                {
                    Id = user.Id,
                    UserName = user.UserName
                };
                var roles = await _roleManager.Roles.ToListAsync();
                foreach (var role in roles)
                {
                    userModel.UserRoles.Add(new UserRolesViewModel
                    {
                        RoleId = role.Id,
                        RoleName = role.Name,
                        IsSelected = await _userManager.IsInRoleAsync(user, role.Name)
                    });
                }
                return View("UserRoles", userModel);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]

ChatBotWithSignalR/Views/Shared/_ChatBoxHeader.cshtml
@using ChatBotWithSignalR.Areas.Chat.Models;
@using ChatBotWithSignalR.Views.Shared.Components.Notification;
@model ChatUserViewModel

<link href="~/css/header.css" rel="stylesheet" asp-append-version="true" />

<!-- ======= Header ======= -->
<header id="header" class="header d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a class="logo d-flex align-items-center" asp-area="Chat" asp-controller="Chat" asp-action="Index" style="background-image: linear-gradient(135deg, #4A00E0, #2ebf91 ); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
            <img src="/images/logo.png" alt="logo" asp-append-version="true">
            <span class="d-none d-lg-block">Triangle ChatBot</span>
        </a>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center" >
            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number" id="notificationCount">4</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications" id="notify-wrapper" style="transform: translate(-40px, 51px) !important;">
                    <li class="dropdown-header">
                        You have 4 new notifications
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    @(await Component.InvokeAsync<NotificationViewComponent>(new { loginUserId = Model.Id }))

                    @*<li>
                        <hr class="dropdown-divider">
                    </li>
                    <i class="bi bi-check-circle text-success"></i>
                    <i class="bi bi-x-circle text-danger"></i>
                    <i class="bi bi-info-circle text-primary"></i>

                    <li class="notification-item">
                    </li>*@

                    @*<li>
                        <hr class="dropdown-divider">
                    </li>
                    <li class="dropdown-footer">
                        <a href="#">Show all notifications</a>
                    </li>*@

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->

            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" data-bs-toggle="dropdown" href="#">
                    <img src="@(Model.ProfilePhotoUrl ?? "/images/no-image.png")" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">@Model.FullName</span>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                   @* <li class="dropdown-header">
                        <h6>@Model.FullName</h6>
                        <span>Web Designer</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>*@

                    <li>
                        <a class="dropdown-item d-flex align-items-center" asp-area="Identity" asp-page="/Account/Manage/Index">
                            <i class="bi bi-person"></i>
                            <span>Profile & Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <form id="logoutform" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Chat", new { area = "Chat" })">
                            <a href="javascript:$('#logoutform').submit();" class="dropdown-item d-flex align-items-center">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>&nbsp; Logout
                            </a>
                        </form>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

ChatBotWithSignalR/Views/Shared/_FileShowModal.cshtml
@using Microsoft.Extensions.Configuration;
@inject IConfiguration _config;
@{
    var baseUrl = _config["UseUrls"];
}
<div class="modal" id="modalFileShow">
    <div class="modal-dialog modal-xl modal-dialog-scrollable">
        <div class="modal-content">
            <!-- Modal Header -->
            @*<div class="modal-header" style="padding: 8px 16px !important">
                <h3 class="modal-title"></h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>*@

            <!-- Modal body -->
            <div class="modal-body">
                <embed src="" style="width: 110%; height: 100vh" id="embedEl" />
            </div>
        </div>
    </div>
</div>
<script>
    function showFileInModal(srcValue) {
        //$('.modal-title').text(docTitle);
        document.querySelector('#embedEl').src = `@baseUrl${srcValue}`;
        $(modalFileShow).modal('show');
    }
</script>

ChatBotWithSignalR/Views/Shared/_Layout.cshtml
@using ChatBotWithSignalR.Constant;
@using ChatBotWithSignalR.DTOs;
@using ChatBotWithSignalR.Service;
@using Microsoft.AspNetCore.Identity;
@using Newtonsoft.Json;
@inject IHttpContextAccessor accessor;
@inject CustomSignInManager<ApplicationUser> _signInManager;
@inject UserManager<ApplicationUser> _userManager;
@{
    dynamic msgObject = null;
    if (TempData["Message"] is not null)
    {
        msgObject = (dynamic)JsonConvert.DeserializeObject(TempData["Message"].ToString());
    }
    var status = "";
    var msg = "";
    if (msgObject is not null)
    {
        status = msgObject?.Status;
        msg = msgObject?.Message;
    }
    //if (accessor.HttpContext?.Session.GetString("ToastNotify") is not null)
    //{
    //   var toast =  JsonConvert.DeserializeObject<ToastAppNotification>(accessor.HttpContext.Session.GetString("ToastNotify"));
    //}
    var appUser = await _userManager.GetUserAsync(User);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  Triangle ChatBot</title>

    <partial name="_stylesPartial" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="/ChatBotWithSignalR.styles.css" asp-append-version="true" />*@
    <style>
        footer .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            white-space: nowrap;
            line-height: 60px;
    </style>
</head>
<body>
    @if (_signInManager.IsSignedIn(User) && (await _userManager.IsInRoleAsync(appUser, Roles.SuperAdmin.ToString()) || await _userManager.IsInRoleAsync(appUser, Roles.Admin.ToString())))
    {
        <header class="container">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="Chat" asp-controller="Chat" asp-action="Index" style="background-image: linear-gradient(135deg, #4A00E0, #2ebf91 ); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">Triangle ChatBot</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Role" asp-action="Index">Role</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Chat" asp-controller="Chat" asp-action="Index">ChatBot</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>
    }

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <partial name="_FileShowModal" />
        <partial name="_formModal" />
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2023 - Triangle ChatBot
        </div>
    </footer>
    <partial name="_scriptsPartial" />
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>

        if ('@status' == 'Success') {
            debugger;
            toastr.success(`@msg`, `@status`);
        }
        else if ('@status' == 'Error') {
            toastr.error(`@msg`, `@status`);
        }
        else if ('@status' == 'Warning') {
            toastr.warning(`@msg`, `@status`);
        }
        else if ('@status' == 'Info') {
            toastr.info(`@msg`, `@status`);
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ChatBotWithSignalR/Views/Shared/_formModal.cshtml
<style>
    .modal-header {
        padding: 8px 16px !important;
    }

    .title {
        margin-bottom: 0px !important;
    }

    .icon-close {
        float: right;
        width: 32px;
        height: 32px;
        font-size: 2rem;
        font-weight: 700;
        line-height: 0rem;
        text-shadow: 0 1px 0 #fff;
        color: #F23338 !important;
        transition: width 1s, height 1s, transform 1s;

    }

        .icon-close:hover {
            background: #FEE7E8;
            transform: rotate(90deg);
        }
</style>
@*Modal for create a user group*@
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="modalHeaderTitle" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title title" id="modalHeaderTitle"></h5>
                <span class="icon-close" data-bs-dismiss="modal" aria-label="Close"><i class="bi bi-x"></i></span>
            </div>
            <div class="modal-body" id="modalBody">
            </div>
        </div>
    </div>
</div>
@*Modal for create a user group*@

ChatBotWithSignalR/Views/Shared/_scriptsPartial.cshtml
<environment include="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/lib/select2/js/select2.js"></script>
</environment>
<environment exclude="Development">
    @*jquery js*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"
            integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-src="~/lib/jquery/jquery.min.js"
            asp-fallback-test="window.jQuery"
            asp-suppress-fallback-integrity="true">
    </script>
    @*bootstrap js*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
            asp-fallback-src="~/lib/bootstrap/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.bootstrap"
            asp-suppress-fallback-integrity="true">
    </script>
    @*toastr js*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
            integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-src="~/lib/toastr.js/toastr.min.js"
            asp-fallback-test="window.toastr" asp-fallback-test-property="position"
            asp-suppress-fallback-integrity="true">
    </script>
    @*select2 js*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-rc.0/js/select2.min.js"
            integrity="sha512-4MvcHwcbqXKUHB6Lx3Zb5CEAVoE9u84qN+ZSMM6s7z8IeJriExrV3ND5zRze9mxNlABJ6k864P/Vl8m0Sd3DtQ=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-src="~/lib/select2/js/select2.min.js"
            asp-fallback-test="window.jQuery"
            asp-suppress-fallback-integrity="true">
    </script>
</environment>